language: java
script:
- gradle build
deploy:
  provider: heroku
  api_key:
    secure: XwsPr+AiHo4yreSBn8ns1ygdlO6W3GXsVfxE//pALWeX9Bxq1K2UoaiM1xISCyPBKsXsS3BJyswhomGBEWgC5b2D+I1KC8JnH0sN9EciMk7p3pVVbOvzGR7Xh97POyMzEVhJD1ltRY5Sivap0gbT/tfk2KBpERVBcQquACNLbiHrRUuQlbIzS07czblJ9OqoytODfMNEqhGtv3XzkCQQgOY2Z7Hh8OKKc8yesWnWvWDXetmNL1081EJybzYE0QLnTJUw000hM52ncbo7E/UoOUDZoM7n7XVaetjVmy1tiSoekIlA5GDyF4ORNkYHwWLrckVbOvBWJ0tPWmyir7nI6nZ433P8WFYVMfNU6DQsKdf46oJGZjcXd5mfv9V+oDbNMlGm58OQ+q/PC0NGfpg3WyXuZ07uribkhQ/4l0M4fwlq8StclcrflTCVtP+yjDYxwWkAp0L/ogROCfqdKOEkuRGWsHtNpjHXDYkIYoqPJ/Hywp4ijjS1nNgbB6zwtDLDvfrch4R4Hm3TOsvEBJdQEzQagxf0+cnh34Lgk4zeIF466UmAZzIV9M4rePDIGy5m6tKdXNNXDL7MeX4/29Ih8HNGQSKwojjO3jfPlXA2W0gOuzrubmI1EHODE3qRuoyho0cUYi9GhntjPaiq5A5L7T9eWafPTfml17lkGmtN3PE=
  app: petadoptionsystem-backend-04-n
  on: master
